### ISSUE TITLE
[bug] Regression on config path-traversal

### ISSUE THREAD

**Issue by PyUser5** [rochacbruno/dynaconf#160]
**Describe the bug**
Configuration is not read correctly for the parent directories

**To Reproduce**
```
 /tmp/test$ find .
.
./test2
./.env

/tmp/test$ ipython3 -c "from dynaconf import settings; print(settings.ENV_FOR_DYNACONF)"
testavalue1

/tmp/test$ cd test2
/tmp/test/test2$ ipython3 -c "from dynaconf import settings; print(settings.ENV_FOR_DYNACONF)"
DEVELOPMENT

/tmp/test/test2$ cat ../.env
ENV_FOR_DYNACONF=testavalue1
```

2. Having the following config files:

see above

3. Having the following app code:

see above

4. Executing under the following environment
conda
Python 3.7.3

**Expected behavior**

Reading the file from the parent directory iff  it does not exist in the current dir.

**Debug output**

<details>
<summary> Debug Output </summary>

```bash

export `DEBUG_LEVEL_FOR_DYNACONF=true` reproduce your problem and paste the output here

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-065bd64b7197> in <module>
----> 1 from dynaconf import settings; print(settings.ENV_FOR_DYNACONF)

~/miniconda3/envs/smr/lib/python3.7/site-packages/dynaconf/__init__.py in <module>
      1 # coding: utf-8
----> 2 from dynaconf.base import LazySettings
      3 from dynaconf.validator import Validator, ValidationError
      4 from dynaconf.contrib import FlaskDynaconf, DjangoDynaconf
      5 

~/miniconda3/envs/smr/lib/python3.7/site-packages/dynaconf/base.py in <module>
      6 
      7 from dynaconf import default_settings
----> 8 from dynaconf.loaders import (
      9     default_loader,
     10     settings_loader,

~/miniconda3/envs/smr/lib/python3.7/site-packages/dynaconf/loaders/__init__.py in <module>
      2 from dynaconf import constants as ct
      3 from dynaconf import default_settings
----> 4 from dynaconf.loaders import (
      5     yaml_loader, toml_loader, json_loader, ini_loader, py_loader
      6 )

~/miniconda3/envs/smr/lib/python3.7/site-packages/dynaconf/loaders/yaml_loader.py in <module>
      4 from warnings import warn
      5 from dynaconf import default_settings
----> 6 from dynaconf.loaders.base import BaseLoader
      7 from dynaconf.constants import YAML_EXTENSIONS
      8 from dynaconf.utils import object_merge

~/miniconda3/envs/smr/lib/python3.7/site-packages/dynaconf/loaders/base.py in <module>
      5 
      6 
----> 7 logger = raw_logger()
      8 
      9 

~/miniconda3/envs/smr/lib/python3.7/site-packages/dynaconf/utils/__init__.py in raw_logger()
     68         return setup_logger(
     69             "dynaconf",
---> 70             level=getattr(logging, level)
     71         )
     72     except ImportError:  # pragma: no cover

AttributeError: module 'logging' has no attribute 'true'

```

</details>

**Environment (please complete the following information):**
 - OS:  Linux/Ubuntu18.04
 - Dynaconf Version 2.0.0
 - Frameworks in use: Flask

**Additional context**

works perfectly in dynaconf < 2.0

**Comment by rochacbruno** [comment]
@PyUser5 fixed in https://github.com/rochacbruno/dynaconf/pull/161 (release of 2.0.1will include it, to be released on Monday, Apr 22)
